### ISSUE TITLE
Outdated blz file

### ISSUE THREAD

**Issue by dfens** [softwareinmotion/ibanizator#8]
Hello,
blz files seems to be outdated so:
- where do you get it from? Or can you update gem ?

**Comment by JGantner** [comment]
Hello,

sorry for the late response. Just realized your comment a few minutes ago. The data comes from the "Deutsche Bundesbank" as stated in the README. Non the less I updated the db and pushed a new version to rubygems.

**Comment by dfens** [comment]
thanks!
